root: true
env:
  es2020: true
  node: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module

plugins:
  - '@typescript-eslint'

rules:
  '@typescript-eslint/no-empty-interface': off
  arrow-body-style: off
  class-methods-use-this: off
  import/extensions:
    - error
    - ignorePackages
    - js: never
      ts: never

  import/prefer-default-export: off
  max-len: [error, 100]
  new-parens: [error, never]
  no-duplicate-imports: error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 0

  operator-linebreak: [error, after]
